/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// SubscribeRate struct for SubscribeRate
type SubscribeRate struct {
	SubscribeThrottlingRatePerConsumer int32 `json:"subscribeThrottlingRatePerConsumer,omitempty"`
	RatePeriodInSecond int32 `json:"ratePeriodInSecond,omitempty"`
}
