/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PostSchemaResponse struct for PostSchemaResponse
type PostSchemaResponse struct {
	Version map[string]interface{} `json:"version,omitempty"`
}
