/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// GetAllVersionsSchemaResponse struct for GetAllVersionsSchemaResponse
type GetAllVersionsSchemaResponse struct {
	GetSchemaResponses []GetSchemaResponse `json:"getSchemaResponses,omitempty"`
}
