/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// LongSchemaVersion struct for LongSchemaVersion
type LongSchemaVersion struct {
	Version int64 `json:"version,omitempty"`
}
