/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// DispatchRate struct for DispatchRate
type DispatchRate struct {
	DispatchThrottlingRateInMsg int32 `json:"dispatchThrottlingRateInMsg,omitempty"`
	DispatchThrottlingRateInByte int64 `json:"dispatchThrottlingRateInByte,omitempty"`
	RatePeriodInSecond int32 `json:"ratePeriodInSecond,omitempty"`
}
