/*
 * Pulsar Admin REST API
 *
 * This provides the REST API for admin operations
 *
 * API version: v2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// IsCompatibilityResponse struct for IsCompatibilityResponse
type IsCompatibilityResponse struct {
	SchemaCompatibilityStrategy string `json:"schemaCompatibilityStrategy,omitempty"`
	Compatibility bool `json:"compatibility,omitempty"`
}
